defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    study_name: default_study
    storage: null
    n_trials: 20
    n_jobs: 1
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
      consider_prior: true
