type: catboost
params:
  iterations: 1000
  learning_rate: 0.03
  depth: 6
  l2_leaf_reg: 3
  loss_function: RMSE
  eval_metric: RMSE
  random_seed: ${random_seed}
  verbose: 100
  early_stopping_rounds: 50
