name: lightgbm
type: spread
target: spread_target

params:
  n_estimators: 500
  learning_rate: 0.05
  max_depth: -1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
  min_child_samples: 40
  lambda_l1: 0.0
  lambda_l2: 0.0
