# @package _global_

defaults:
  - override hydra/sweeper: optuna
  - override hydra/launcher: joblib

core:
  train_years: "2019,2021,2022,2023"
  test_year: 2024
  data_root: null
  output_dir: ./reports/optimization
  fast: false

model:
  _target_: sklearn.linear_model.Ridge

target: spread

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: "minimize"
    study_name: "ridge_spread_optimization"
    n_trials: 10
    n_jobs: 1
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
