name: ensemble_v1
type: ensemble
params:
  weights: [0.5, 0.5]
  models:
    - type: linear_regression
      params:
        alpha: 10.0
    - type: xgboost
      params:
        n_estimators: 1000
        learning_rate: 0.05
        max_depth: 6
        objective: reg:squarederror
        random_state: 42
target: spread_target
