name: points_for_xgboost
type: xgboost
target: points_target  # Placeholder
adjustment_iteration: 2
calibration_bias: 0.0
calibration_type: null
calibration_year: null

# Default Parameters (Performed best in ensemble)
params:
  n_estimators: 1000
  learning_rate: 0.05
  max_depth: 6
  subsample: 0.8
  colsample_bytree: 0.8
  objective: reg:squarederror
  n_jobs: -1
  random_state: 42
