name: gradient_boosting
type: points_for

params:
  n_estimators: 200
  learning_rate: 0.1
  max_depth: 3
  subsample: 0.8

hydra:
  sweeper:
    params:
      model.params.n_estimators: choice(100,200,400)
      model.params.learning_rate: choice(0.05,0.1,0.2)
      model.params.max_depth: choice(2,3,4)
      model.params.subsample: choice(0.6,0.8,1.0)
