# Quantile Regression Configuration
# Predicts 10th, 50th, and 90th percentiles using MultiQuantile loss.

model_params:
  loss_function: "MultiQuantile:alpha=0.1,0.5,0.9"
  eval_metric: "MultiQuantile:alpha=0.1,0.5,0.9"
  iterations: 1000
  learning_rate: 0.03
  depth: 6
  l2_leaf_reg: 3.0
  random_seed: 42
  verbose: 0
