# Residual CatBoost Configuration
type: catboost
params:
  loss_function: RMSE
  depth: 6
  learning_rate: 0.05
  iterations: 1000
  random_seed: 42
  verbose: 0
  l2_leaf_reg: 3
  early_stopping_rounds: 50
