name: catboost
type: catboost
target: spread_target
adjustment_iteration: 2
calibration_bias: 1.4  # Systematic bias correction (2024 calibration analysis)

params:
  depth: 6
  learning_rate: 0.05
  iterations: 800
  l2_leaf_reg: 3.0
  subsample: 0.8
  random_seed: 42
