name: xgboost
type: total
target: total_target

params:
  objective: reg:squarederror
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 3
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
