type: xgboost
params:
  n_estimators: 1000
  learning_rate: 0.03
  max_depth: 6
  min_child_weight: 3
  subsample: 0.8
  colsample_bytree: 0.8
  gamma: 0
  reg_alpha: 0
  reg_lambda: 1
  objective: reg:squarederror
  random_state: ${random_seed}

