# Unified Windsurf AI Flows
# Use the appropriate S.C.A.F.F. prompt for your task:
#   - scaff_feature_dev.md for feature development
#   - scaff_debugging.md for debugging
#   - scaff_code_review.md for code review

- name: Feature-Development
  steps:
    - load: documents/execution/session_logs/
    - load: documents/_current_context.md
    - prompt: .windsurf/prompts/scaff_feature_dev.md
    - launch: cascade_chat

- name: Debugging
  steps:
    - load: documents/execution/session_logs/
    - load: documents/_current_context.md
    - prompt: .windsurf/prompts/scaff_debugging.md
    - launch: cascade_chat

- name: Code-Review
  steps:
    - load: documents/execution/session_logs/
    - load: documents/_current_context.md
    - prompt: .windsurf/prompts/scaff_code_review.md
    - launch: cascade_chat
