# Optuna Search Space for CatBoost
defaults:
  - _self_

# Optimization target
metric: RMSE
direction: minimize

# Number of trials
n_trials: 20

# Sampler configuration
sampler:
  _target_: optuna.samplers.TPESampler
  seed: 42

# Search space
params:
  learning_rate:
    type: float
    low: 0.001
    high: 0.1
    log: true
  depth:
    type: int
    low: 4
    high: 10
  l2_leaf_reg:
    type: float
    low: 1.0
    high: 10.0
    log: true
  random_strength:
    type: float
    low: 1.0
    high: 10.0
  bagging_temperature:
    type: float
    low: 0.0
    high: 1.0
