# Optuna Search Space for XGBoost
defaults:
  - _self_

# Optimization target
metric: RMSE
direction: minimize

# Number of trials
n_trials: 20

# Sampler configuration
sampler:
  _target_: optuna.samplers.TPESampler
  seed: 42

# Search space
params:
  learning_rate:
    type: float
    low: 0.001
    high: 0.1
    log: true
  max_depth:
    type: int
    low: 3
    high: 10
  min_child_weight:
    type: int
    low: 1
    high: 10
  subsample:
    type: float
    low: 0.5
    high: 1.0
  colsample_bytree:
    type: float
    low: 0.5
    high: 1.0
  gamma:
    type: float
    low: 0.0
    high: 5.0
  reg_alpha:
    type: float
    low: 0.0
    high: 1.0
  reg_lambda:
    type: float
    low: 0.0
    high: 10.0
    log: true
