year: 2024
week: 13
model_year: 2024
output_dir: artifacts/reports
prediction_mode: points_for_registry
bankroll: 10000
max_weekly_exposure_fraction: 0.15
max_weekly_bets: 12
max_single_bet_fraction: 0.05

model_registry:
  spread_models: 
    - spread_catboost_pruned_seed_1
    - spread_catboost_pruned_seed_2
    - spread_catboost_pruned_seed_3
    - spread_catboost_pruned_seed_4
    - spread_catboost_pruned_seed_5
  total_models: 
    - cfb_total_catboost
  points_for_home_models:
    - points_for_home_seed_1
    - points_for_home_seed_2
    - points_for_home_seed_3
    - points_for_home_seed_4
    - points_for_home_seed_5
  points_for_away_models:
    - points_for_away_seed_1
    - points_for_away_seed_2
    - points_for_away_seed_3
    - points_for_away_seed_4
    - points_for_away_seed_5

betting:
  spread_threshold: 5.0
  total_threshold: 3.5
  spread_std_dev_threshold: null
  total_std_dev_threshold: null

points_for:
  spread_std: 14.0
  total_std: 14.0
model_dir: artifacts/models
