year: 2025
week: 14
model_year: 2025
output_dir: artifacts/reports
prediction_mode: points_for_registry
bankroll: 10000
max_weekly_exposure_fraction: 0.15
max_weekly_bets: 12
max_single_bet_fraction: 0.05

model_registry:
  spread_models: 
    - spread_catboost_ppr_seed_5
  total_models: 
    - totals_xgboost_ppr_seed_5

# Weekly Betting Configuration
# Based on 2024 threshold analysis (Nov 2024)

# Spread threshold optimized for CatBoost model
spread_edge_threshold: 5.0  # CatBoost achieves 2.3% ROI at this threshold

# Total threshold optimized for XGBoost model  
# Optimization (Dec 2025): >5% ROI at 6.0, >9% ROI at 8.0. Setting to 7.5.
total_edge_threshold: 7.5

# Kelly fraction for position sizing
kelly_fraction: 0.25

betting:
  spread_threshold: 5.0  # Must match spread_edge_threshold
  total_threshold: 7.5   # Must match total_edge_threshold
  spread_std_dev_threshold: null
  total_std_dev_threshold: null

points_for:
  spread_std: 14.0
  total_std: 14.0
model_dir: artifacts/models
