year: 2025
week: 14
model_year: 2025
output_dir: artifacts/reports
prediction_mode: points_for_registry
bankroll: 10000
max_weekly_exposure_fraction: 0.15
max_weekly_bets: 12
max_single_bet_fraction: 0.05

model_registry:
  spread_models: 
    - cfb_points_for_home
    - cfb_points_for_away
  total_models: 
    - totals_catboost_baseline_v1

# Weekly Betting Configuration
# Based on 2024 threshold analysis (Nov 2024)

# Spread threshold optimized for CatBoost model
spread_edge_threshold: 5.0  # CatBoost achieves 2.3% ROI at this threshold

# Total threshold optimized for XGBoost model  
total_edge_threshold: 5.5  # XGBoost achieves 5.5% ROI at this threshold

# Kelly fraction for position sizing
kelly_fraction: 0.25

betting:
  spread_threshold: 10.0
  total_threshold: 3.5
  spread_std_dev_threshold: null
  total_std_dev_threshold: null

points_for:
  spread_std: 14.0
  total_std: 14.0
model_dir: artifacts/models
