name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Dependencies
        run: ~/.cargo/bin/uv sync --system-site-packages

      - name: Run Linters and Formatters
        run: |
          ~/.cargo/bin/uv run ruff check .
          ~/.cargo/bin/uv run ruff format --check .

      - name: Run Security Scans
        run: |
          ~/.cargo/bin/uv run bandit -r src/
          ~/.cargo/bin/uv pip freeze | ~/.cargo/bin/uv run safety check --stdin

      - name: Run Tests
        run: ~/.cargo/bin/uv run pytest

  test-notebooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Configure uv
      run: |
        source $HOME/.cargo/env
        uv sync --all-extras
    - name: Run notebook tests
      run: |
        source $HOME/.cargo/env
        uv run python scripts/test_notebooks.py
